version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: dashboard_db
      POSTGRES_USER: markus
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata_monitor:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monitor_user -d monitor_db"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  pgdata_monitor:
