"""events

Revision ID: 2885c8507c67
Revises: 
Create Date: 2025-08-14 16:55:15.428791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2885c8507c67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Renombrar la tabla en lugar de eliminarla
    op.rename_table('events', 'event')

    # Si añadiste/quitaste columnas, usa op.add_column / op.drop_column aquí
    op.add_column('event', sa.Column('ts', sa.DateTime(), nullable=False))
    op.add_column('event', sa.Column('source', sa.String(), nullable=False))
    op.add_column('event', sa.Column('url', sa.String(), nullable=True))
    op.add_column('event', sa.Column('title', sa.String(), nullable=True))
    op.add_column('event', sa.Column('duration_sec', sa.Integer(), nullable=False))
    op.add_column('event', sa.Column('category', sa.String(), nullable=True))
    op.add_column('event', sa.Column('subcategory', sa.String(), nullable=True))
    op.add_column('event', sa.Column('productive_score', sa.Float(), nullable=False))

    # Crear la nueva tabla goals
    op.create_table(
        'goals',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goals')

    # Eliminar las columnas nuevas de event si es necesario
    op.drop_column('event', 'productive_score')
    op.drop_column('event', 'subcategory')
    op.drop_column('event', 'category')
    op.drop_column('event', 'duration_sec')
    op.drop_column('event', 'title')
    op.drop_column('event', 'url')
    op.drop_column('event', 'source')
    op.drop_column('event', 'ts')

    # Renombrar de vuelta
    op.rename_table('event', 'events')
    # ### end Alembic commands ###
