"""events updated

Revision ID: fe50dc61df5d
Revises: 2885c8507c67
Create Date: 2025-08-14 17:08:08.635077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe50dc61df5d'
down_revision: Union[str, Sequence[str], None] = '2885c8507c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_event_ts'), 'event', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_ts'), table_name='event')
    # ### end Alembic commands ###
